
# Install and configure the necessary dependencies
sudo yum install -y curl policycoreutils-python openssh-server
sudo systemctl enable sshd
sudo systemctl start sshd
sudo firewall-cmd --permanent --add-service=http
sudo firewall-cmd --permanent --add-service=https
sudo systemctl reload firewalld

# Install Postfix
sudo yum install postfix
sudo systemctl enable postfix
sudo systemctl start postfix

# Gitlab Package and Install
curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.rpm.sh | sudo bash
sudo EXTERNAL_URL="{{ gitlab_url_service }}" yum install -y gitlab-ee
